plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.nativegooglesignin'
version = '0.1.0'

android {
  namespace "expo.modules.nativegooglesignin"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    consumerProguardFiles 'consumer-rules.pro'
  }
  lintOptions {
    abortOnError false
  }
  testOptions {
    unitTests.returnDefaultValues = true
  }
}

dependencies {
  implementation 'androidx.credentials:credentials:1.6.0'
  implementation 'androidx.credentials:credentials-play-services-auth:1.6.0'
  implementation 'com.google.android.libraries.identity.googleid:googleid:1.2.0'

  testImplementation 'junit:junit:4.13.2'
}
